### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by yarikoptic** [con/tributors#77]
To mitigate #76 I switched to use the most recent tag 0.0.21-node-20 .  Container built fine but execution crashed 

https://github.com/datalad/datalad/actions/runs/5193213913/jobs/9363452090

```
.all-contributorsrc already exists.
tributors update unset --thresh 1 --skip-users manbat bhanuprasad14 yetanothertestuser bobknob23987 --allcontrib-type code
INFO:allcontrib:Updating .all-contributorsrc
INFO:allcontrib:Updating .tributors cache from .all-contributorsrc
INFO:github:Alejandro de la Vega: found more than 1 result, run with --interactive mode to select.
INFO:github:Alejandro de la Vega: found more than 1 result, run with --interactive mode to select.
INFO:github:Alejandro de la Vega: found more than 1 result, run with --interactive mode to select.
INFO:github:Christian Mönch: found more than 1 result, run with --interactive mode to select.
INFO:github:Christian Mönch: found more than 1 result, run with --interactive mode to select.
INFO:github:Matt Cieslak: found more than 1 result, run with --interactive mode to select.
INFO:github:Robin Schneider: found more than 1 result, run with --interactive mode to select.
INFO:github:Robin Schneider: found more than 1 result, run with --interactive mode to select.
INFO:github:Sin Kim: found more than 1 result, run with --interactive mode to select.
INFO:github:Sin Kim: found more than 1 result, run with --interactive mode to select.
INFO:github:Michael Burgardt: found more than 1 result, run with --interactive mode to select.
INFO:github:Michał Szczepanik: found more than 1 result, run with --interactive mode to select.
INFO:github:Michał Szczepanik: found more than 1 result, run with --interactive mode to select.
INFO:github:Taylor Olson: found more than 1 result, run with --interactive mode to select.
INFO:github:Taylor Olson: found more than 1 result, run with --interactive mode to select.
INFO:github:James Kent: found more than 1 result, run with --interactive mode to select.
INFO:github:James Kent: found more than 1 result, run with --interactive mode to select.
INFO:github:Chris Lamb: found more than 1 result, run with --interactive mode to select.
INFO:github:Chris Lamb: found more than 1 result, run with --interactive mode to select.
INFO:github:Matt McCormick: found more than 1 result, run with --interactive mode to select.
INFO:github:Matt McCormick: found more than 1 result, run with --interactive mode to select.
INFO:github:Vicky C Lau: found more than 1 result, run with --interactive mode to select.
INFO:github:Vicky C Lau: found more than 1 result, run with --interactive mode to select.
INFO:github:Austin Macdonald: found more than 1 result, run with --interactive mode to select.
INFO:github:Austin Macdonald: found more than 1 result, run with --interactive mode to select.
WARNING:tributors:allcontrib does not support updating from orcids.
WARNING:tributors:allcontrib does not support updating from email.
INFO:    zenodo:Updating .zenodo.json
INFO:    zenodo:Updating .tributors cache from .zenodo.json
Traceback (most recent call last):
  File "/opt/conda/bin/tributors", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/tributors/client/__init__.py", line 179, in main
    main(args, extra)
  File "/opt/conda/lib/python3.10/site-packages/tributors/client/update.py", line [65](https://github.com/datalad/datalad/actions/runs/5193213913/jobs/9363452090#step:5:66), in main
    client.update(
  File "/opt/conda/lib/python3.10/site-packages/tributors/main/__init__.py", line 127, in update
    client.update(thresh=thresh, from_resources=resources)
  File "/opt/conda/lib/python3.10/site-packages/tributors/main/parsers/zenodo.py", line 1[90](https://github.com/datalad/datalad/actions/runs/5193213913/jobs/9363452090#step:5:91), in update
    self.update_cache()
  File "/opt/conda/lib/python3.10/site-packages/tributors/main/parsers/base.py", line 141, in update_cache
    self.update_lookup()
  File "/opt/conda/lib/python3.10/site-packages/tributors/main/parsers/zenodo.py", line 221, in update_lookup
    value = lookup[cache]["orcid"][field]
TypeError: unhashable type: 'dict'
```

<details>
<summary>Not sure why it complains about more than 1 result since on a sample name -- has just one entry in .tributors</summary> 

```shell
❯ git grep 'James Kent'
.all-contributorsrc:            "name": "James Kent",
.tributors:        "name": "James Kent",
CHANGELOG.md:- James Kent (@jdkent)
README.md:      <td align="center" valign="top" width="14.28%"><a href="https://jdkent.github.io/"><img src="https://avatars.githubusercontent.com/u/12564882?v=4?s=100" width="100px;" alt="James Kent"/><br /><sub><b>James Kent</b></sub></a><br /><a href="https://github.com/datalad/datalad/commits?author=jdkent" title="Code">💻</a></td>
docs/source/changelog.rst:-  James Kent (@jdkent)

```
</details>

**Comment by yarikoptic** [comment]
FWIW: reproduced locally -- looking into it
